[network]
name = "testnet"
stacks_node_rpc_address = "https://api.testnet.hiro.so"
deployment_fee_rate = 10

[accounts.deployer]
mnemonic = "radio engage west lemon video adjust inmate return casual game list offer legal defense drive open tortoise join farm time jacket practice wave illness"
